### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MenQiuYT** [dbm-network/mods#243]
Set Voice channel perms 

TypeError: Cannot read property '0' of undefined

**Comment by HernoooX** [comment]
Buy DBM

**Comment by Almeeida** [comment]
Make sure you are using DBM **beta**, @MenQiuYT.

### Installing the beta version
1. Close DBM
1. Open Steam
1. Open your software library
1. Right click Discord Bot Maker
1. Select Properties (at the bottom)
1. Select Betas
1. Select beta in the drop down menu (no key is required)
1. DBM should update now. Otherwise restart Steam.
