### ISSUE TITLE
Error with Event "Edit Channel", Action #3: TypeError: this.getVoiceChannel is not a function

### ISSUE THREAD

**Issue by Biit-s** [dbm-network/mods#265]
I try to make my bot edit one voice channel with "Players | [Numbers of members on dc]" but the dbm send this issue on the console.

Error with Event "Edit Channel", Action #3: TypeError: this.getVoiceChannel is not a function
actions: https://prnt.sc/qt7wsr

**bit#2298**

**Comment by Almeeida** [comment]
Make sure you have DBM **beta**, @Biit-s.

### Installing the beta version
1. Close DBM
1. Open Steam
1. Open your software library
1. Right-click Discord Bot Maker
1. Select Properties (at the bottom)
1. Select Betas
1. Select beta in the drop-down menu (no key is required)
1. DBM should update now. Otherwise restart Steam.
