### ISSUE TITLE
canvas bug

### ISSUE THREAD

**Issue by sajjadRetro** [dbm-network/mods#641]
canvas image actions do not work correctly but old image actions works fix it, please

**Comment by Lucasamiel0406** [comment]
Explain better what is happening, what errors you get, what the console/bot logs say.

**Comment by sajjadRetro** [comment]
> Explain better what is happening, what errors you get, what the console/bot logs say.
that's what I received in cmd 

> Error: Cannot find module 'canvas'

**Comment by Winside-Dev** [comment]
npm i canvas

> > Explain better what is happening, what errors you get, what the console/bot logs say.
> > that's what I received in cmd
> 
> > Error: Cannot find module 'canvas'

npm i canvas

**Comment by sajjadRetro** [comment]
> > > Explain better what is happening, what errors you get, what the console/bot logs say.
> > > that's what I received in cmd
> > 
> > 
> > > Error: Cannot find module 'canvas'
> 
> npm i canvas

i have to type it in cmd?

**Comment by Thaliruth1** [comment]
> > > > Explain better what is happening, what errors you get, what the console/bot logs say.
> > > > that's what I received in cmd
> > > 
> > > 
> > > > Error: Cannot find module 'canvas'
> > 
> > 
> > npm i canvas
> 
> thank you but i recived a new error
> "Error with the command "Canvas Create Image", Action #1:
> canvas.node is not a valid Win32 application."

This is not a mod bug! The Mo works fine for me. Google times after the error because you get, then you will find a lot. I also have from time to time that with Win32, since it helps mostly Canvas and co. reinstall. But it is not because of the mod!

Also, it is not the mod if Canvas can not be found, it is here on you and your non-existent knowledge unfortunately.
