### ISSUE TITLE
Youtube mods not working.

### ISSUE THREAD

**Issue by Kamilowskyy8** [dbm-network/mods#657]
**Describe the bug**
Mods: `youtube_info_MOD.js`, `youtube_search_MOD.js`, `store_youtube_channel_info_MOD.js` and `play_youtube_playlist_MOD.js` not working in Discord Bot Maker. After carefully creating a command with these actions, the command behaves as if it did not see the actions. No bugs in the console. FFMPEG installed and Updated Music Library. All mods are installed to DBM and Project directory.
**My Module Manager:**
- discord.js _^12.2.0_
- fstorm _latest_
- jimp _latest_
- libsodium-wrappers _latest_
- opusscript _latest_
- ytdl-core _latest_
- node-cron _latest_
- simple-youtube-api _latest_
- ytsr _latest_
- valid-url _latest_

**To Reproduce**
This seems to be a bug with the code itself in the mods listed above.

**Comment by Lucasamiel0406** [comment]
I tested almost actions with test commands and even with my old rawdatas, `Youtube Search` I stated many times in DBM Mods that is broken because of its node package, and for me `Youtube Info` didn't worked properly, but I literally listened to 10 songs before restarting my bot using `Play Youtube Playlist` and `Store Youtube Channel Info` worked just fine, I had to wait couple seconds but worked just fine, if all them don't work for you, you did something wrong.
Before coming here creating a whole bug report, use the server to make sure ALL ACTIONS don't work.

**Comment by Kamilowskyy8** [comment]
Additionally, I added modules: `youtube-info` because I didn't own it.
For me, these 2 actions still don't work. Could I ask you to give me your installed modules?

**Comment by Lucasamiel0406** [comment]
Unfortunately I can't just give you files like that, but `ytpl` is a module for `Youtube Playlist` and the channel info action uses `yt-channel-info` package. Install them with your console.

**Comment by Kamilowskyy8** [comment]
This is what I meant for you to give me the names of the modules to be installed. **Thank you!**
But now there's another problem. I have an error in the console. I have attached a screenshot.
![image](https://user-images.githubusercontent.com/82074300/113965420-9b37ae80-982d-11eb-97b7-1f6d11a016d4.png)

**Comment by TheMonDon** [comment]
My new PR #672 fixes all the issues you have.
